// NewFlight
export const NEW_FLIGHT_NEXT_STEP = 'NEW_FLIGHT_NEXT_STEP';
export const NEW_FLIGHT_PREV_STEP = 'NEW_FLIGHT_PREV_STEP';
export const NEW_FLIGHT_SET_STEP_FULFILLMENT =
  'NEW_FLIGHT_SET_STEP_FULFILLMENT';

// FlightFinder
export const FLIGHT_FINDER_GET_CITIES = 'FLIGHT_FINDER_GET_CITIES';
export const FLIGHT_FINDER_CHANGE_DATE_START =
  'FLIGHT_FINDER_CHANGE_DATE_START';
export const FLIGHT_FINDER_CHANGE_DATE_END = 'FLIGHT_FINDER_CHANGE_DATE_END';
export const FLIGHT_FINDER_UPDATE_FILTERS = 'FLIGHT_FINDER_UPDATE_FILTERS';
export const FLIGHT_FINDER_UPDATE_FLIGHTS = 'FLIGHT_FINDER_UPDATE_FLIGHTS';
export const FLIGHT_FINDER_SELECT_FLIGHT = 'FLIGHT_FINDER_SELECT_FLIGHT';
export const FLIGHT_FINDER_TOGGLE_REVERSE_FLIGHT =
  'FLIGHT_FINDER_TOGGLE_REVERSE_FLIGHT';
