// NewFlight
export const NEW_FLIGHT_NEXT_STEP = 'NEW_FLIGHT_NEXT_STEP';
export const NEW_FLIGHT_PREV_STEP = 'NEW_FLIGHT_PREV_STEP';
export const NEW_FLIGHT_SET_STEP_FULFILLMENT =
  'NEW_FLIGHT_SET_STEP_FULFILLMENT';
export const NEW_FLIGHT_UNMOUNT = 'NEW_FLIGHT_UNMOUNT';

// FlightFinder
export const FLIGHT_FINDER_REQUEST_CITIES = 'FLIGHT_FINDER_REQUEST_CITIES';
export const FLIGHT_FINDER_GET_CITIES = 'FLIGHT_FINDER_GET_CITIES';
export const FLIGHT_FINDER_CHANGE_DATE_START =
  'FLIGHT_FINDER_CHANGE_DATE_START';
export const FLIGHT_FINDER_CHANGE_DATE_END = 'FLIGHT_FINDER_CHANGE_DATE_END';
export const FLIGHT_FINDER_UPDATE_FILTERS = 'FLIGHT_FINDER_UPDATE_FILTERS';
export const FLIGHT_FINDER_REQUEST_FLIGHTS = 'FLIGHT_FINDER_REQUEST_FLIGHTS';
export const FLIGHT_FINDER_RECEIVE_FLIGHTS = 'FLIGHT_FINDER_RECEIVE_FLIGHTS';
export const FLIGHT_FINDER_SELECT_FLIGHT = 'FLIGHT_FINDER_SELECT_FLIGHT';
export const FLIGHT_FINDER_TOGGLE_REVERSE_FLIGHT =
  'FLIGHT_FINDER_TOGGLE_REVERSE_FLIGHT';

// PlacePicker
export const PLACE_PICKER_REQUEST_ALL_PLACES =
  'PLACE_PICKER_REQUEST_ALL_PLACES';
export const PLACE_PICKER_GET_ALL_PLACES = 'PLACE_PICKER_GET_ALL_PLACES';
export const PLACE_PICKER_TOGGLE_PLACE = 'PLACE_PICKER_TOGGLE_PLACE';
export const PLACE_PICKER_TOGGLE_LUGGAGE_REQUIREMENT =
  'PLACE_PICKER_TOGGLE_LUGGAGE_REQUIREMENT';
export const PLACE_PICKER_CHANGE_LUGGAGE_AMOUNT =
  'PLACE_PICKER_CHANGE_LUGGAGE_AMOUNT';
export const PLACE_PICKER_VALIDATE_PLACES = 'PLACE_PICKER_VALIDATE_PLACES';
export const PLACE_PICKER_REQUEST_BOOKING_TEMPORARILY =
  'PLACE_PICKER_REQUEST_BOOKING_TEMPORARILY';
export const PLACE_PICKER_BOOK_PLACES_TEMPORARILY =
  'PLACE_PICKER_BOOK_PLACES_TEMPORARILY';

// PriceConfirmator
export const PRICE_CONFIRMATOR_CONFIRM_ORDER =
  'PRICE_CONFIRMATOR_CONFIRM_ORDER';
export const PRICE_CONFIRMATOR_CANCEL_ORDER = 'PRICE_CONFIRMATOR_CANCEL_ORDER';

//Modal
export const MODALS_OPEN = 'MODALS_OPEN';
export const MODALS_CLOSE = 'MODALS_CLOSE';

// Orders
export const ORDERS_REQUEST_ORDER_INFO = 'ORDERS_REQUEST_ORDER_INFO';
export const ORDERS_GET_ORDER_INFO = 'ORDERS_GET_ORDER_INFO';
export const ORDERS_REQUEST_ALL = 'ORDERS_REQUEST_ALL';
export const ORDERS_RECEIVE_ALL = 'ORDERS_RECEIVE_ALL';

// Dropdown
export const DROPDOWN_TOGGLE = 'DROPDOWN_TOGGLE';
export const DROPDOWN_SET_FILTER = 'DROPDOWN_SET_FILTER';

// Profile
export const PROFILE_REQUEST_INFO = 'PROFILE_REQUEST_INFO';
export const PROFILE_GET_INFO = 'PROFILE_GET_INFO';
export const PROFILE_EDIT_USERNAME = 'PROFILE_EDIT_USERNAME';
export const PROFILE_CHANGE_USERNAME = 'PROFILE_CHANGE_USERNAME';
export const PROFILE_CANCEL_EDITTING = 'PROFILE_CANCEL_EDITTING';
export const PROFILE_REJECT_EDIT_CONFIRMATION =
  'PROFILE_REJECT_EDIT_CONFIRMATION';
export const PROFILE_CONFIRM_EDITTING = 'PROFILE_CONFIRM_EDITTING';
export const PROFILE_UPLOAD_AVATAR = 'PROFILE_UPLOAD_AVATAR';

// Registration
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_DESTROY = 'REGISTRATION_DESTROY';

// Authorization
export const AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export const AUTHORIZATION_DESTROY = 'AUTHORIZATION_DESTROY';
export const AUTHORIZATION_LOGOUT = 'AUTHORIZATION_LOGOUT';

export const BOOKING_ADD_LUGGAGE = 'BOOKING_ADD_LUGGAGE';
