import moment from 'moment';
export const tickets = [
  {
    flightId: '4',
    places: [
      {
        number: 1,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 2,
        type: 'econom',
        available: false,
        isPermanently: true,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 3,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-05 14:21'),
      },
      {
        number: 4,
        type: 'business',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-05 14:21'),
      },
      {
        number: 5,
        type: 'business',
        available: false,
        isPermanently: false,
        expiresAt: moment('2018-02-06 17:21'),
      },
      {
        number: 6,
        type: 'business',
        available: false,
        isPermanently: true,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 7,
        type: 'business',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 8,
        type: 'business',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 9,
        type: 'business',
        available: false,
        isPermanently: false,
        expiresAt: moment('2018-02-06 17:21'),
      },
      {
        number: 10,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 11,
        type: 'econom',
        available: false,
        isPermanently: true,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 12,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
    ],
  },
  {
    flightId: '5',
    places: [
      {
        number: 1,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 2,
        type: 'econom',
        available: false,
        isPermanently: true,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 3,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-05 14:21'),
      },
      {
        number: 4,
        type: 'business',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-05 14:21'),
      },
      {
        number: 5,
        type: 'business',
        available: false,
        isPermanently: false,
        expiresAt: moment('2018-02-06 17:21'),
      },
      {
        number: 6,
        type: 'business',
        available: false,
        isPermanently: true,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 7,
        type: 'business',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 8,
        type: 'business',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 9,
        type: 'business',
        available: false,
        isPermanently: false,
        expiresAt: moment('2018-02-06 17:21'),
      },
      {
        number: 10,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 11,
        type: 'econom',
        available: false,
        isPermanently: true,
        expiresAt: moment('2018-02-06 14:21'),
      },
      {
        number: 12,
        type: 'econom',
        available: true,
        isPermanently: false,
        expiresAt: moment('2018-02-06 14:21'),
      },
    ],
  },
];
